# Requirements: https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/planning_your_deployment/assembly_infrastructure-and-system-requirements#ref_RHOCP-software-requirements_planning
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  targetNamespaces: []
  spec: {}
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
spec:
  channel: stable-v1
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-cluster-observability-operator
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-cluster-observability
  namespace: openshift-cluster-observability-operator
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cluster-observability-operator
  namespace: openshift-cluster-observability-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/networking/networking-operators#installing-the-kubernetes-nmstate-operator-CLI_k8s-nmstate-operator
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
  namespace: metallb-system
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator
  namespace: metallb-system
spec:
  channel: stable
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/networking/networking-operators#installing-the-kubernetes-nmstate-operator-CLI_k8s-nmstate-operator
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-nmstate
spec:
  finalizers:
  - kubernetes
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-nmstate
  namespace: openshift-nmstate
spec:
  targetNamespaces:
  - openshift-nmstate
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  installPlanApproval: Automatic
  name: kubernetes-nmstate-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openstack-operators
---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openstack-operator
  namespace: openstack-operators
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openstack-operators
  namespace: openstack-operators
spec:
  channel: stable-v1.0
  installPlanApproval: Automatic
  name: openstack-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---

apiVersion: v1
kind: Namespace
metadata:
  name: openstack
  labels:
    name: openstack
    pod-security.kubernetes.io/enforce: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  name: openshift-storage
