# Due to requirements: https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0/html/planning_your_deployment/assembly_infrastructure-and-system-requirements#ref_RHOCP-software-requirements_planning
# https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/networking/networking-operators#nw-metallb-operator-initial-config_metallb-operator-install
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
