apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: openstack             # Volume group name
        default: true               # This becomes the default StorageClass
        thinPoolConfig:
          name: thin-pool-1         # LVM thin pool name
          sizePercent: 90           # Use 90% of the VG space
          overprovisionRatio: 10    # Allow 10x overprovisioning
        deviceSelector:
          paths:
            - /dev/disk/by-path/pci-0000:65:00.0-scsi-0:2:22:0  # <-- Your block devices with unused space                    
