apiVersion: v1
kind: Secret
metadata:
  name: dataplane-ansible-ssh-private-key-secret
  namespace: openstack
stringData:
  # 1) CONFIGURE private key
  # $ ssh-keygen -f <key_file_name> -N "" -t rsa -b 4096
  #
  # New user creation
  # $ useradd cloud-admin
  # 
  # Uncomment "%wheel  ALL=(ALL)       NOPASSWD: ALL" in visudo
  # $ visudo
  #
  # add .pub as authorized key on new user "cloud-admin" in RHEL 9.4 on compute node
  # example: /home/cloud-admin/.ssh/authorized_keys
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    #PASTE_HERE_PRIVKEY
    -----END OPENSSH PRIVATE KEY-----
  ssh-publickey: # Public key for that private key goes here
  authorized_keys: |
    ["#PASTE_HERE_PUBLICKEY",
     "#ADDITIONAL_PUBLIC_KEY"]
