apiVersion: v1
kind: Secret
metadata:
  name: nova-migration-ssh-key
  namespace: openstack
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # nova private key CONFIGURE
    # ssh-keygen -f ./nova-migration-ssh-key -t ecdsa-sha2-nistp521 -N ''
    # add .pub as authorized key on new user "cloud-admin" in RHEL 9.4 compute node
    -----END OPENSSH PRIVATE KEY-----
  ssh-publickey: # public key part
