apiVersion: v1
kind: Secret
metadata:
  name: subscription-manager
  namespace: openstack
stringData:
  username: # Subscription username (for "subscription-manager register")
  password: # Subscription password
